# Generated by Django 2.0.2 on 2018-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='media/main/data')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
