# Generated by Django 2.0.2 on 2018-04-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_data',
            name='data',
            field=models.FileField(upload_to='static/main/data'),
        ),
    ]
