# Generated by Django 2.0.2 on 2018-04-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180417_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_data',
            name='data',
            field=models.FileField(upload_to='main/static/main/data'),
        ),
    ]
