# Generated by Django 2.0.2 on 2018-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180417_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=70, verbose_name='Crop')),
                ('temp_requirements', models.CharField(max_length=50, verbose_name='Temperature Requirements')),
                ('rainfall_requirement', models.CharField(max_length=50, verbose_name='Rainfall Requirements')),
                ('fertilizer_ha', models.CharField(max_length=100, verbose_name='Fertilizer/Ha')),
            ],
        ),
        migrations.AlterField(
            model_name='csv_data',
            name='data',
            field=models.FileField(upload_to='main/static/main/data'),
        ),
    ]
