# Generated by Django 2.0.2 on 2018-07-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_crop_seasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_seasons',
            old_name='maxRainfall',
            new_name='avgRainfall',
        ),
        migrations.RemoveField(
            model_name='crop_seasons',
            name='minRainfall',
        ),
    ]
