# Generated by Django 2.0.2 on 2018-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180702_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_seasons',
            name='avgTemp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
