# Generated by Django 2.0.2 on 2018-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_crop_seasons_avgtemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_seasons',
            name='avgRainfall',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop_seasons',
            name='avgTemp',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop_seasons',
            name='maxTemp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop_seasons',
            name='minTemp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop_seasons',
            name='period_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
