# Generated by Django 2.0.2 on 2018-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180704_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_seasons',
            name='avgRainfall',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop_seasons',
            name='avgTemp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop_seasons',
            name='maxTemp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop_seasons',
            name='minTemp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop_seasons',
            name='period_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
