# Generated by Django 2.0.2 on 2018-07-27 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20180704_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, choices=[('wheat', 'Wheat'), ('maize', 'Maize')], default='', max_length=8)),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crop_requirements',
            name='expected_yield_acre',
            field=models.CharField(default='000', max_length=100, verbose_name='Expected Yield/Acre'),
        ),
    ]
