# Generated by Django 2.0.2 on 2018-07-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180727_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_requirements',
            name='expected_yield_acre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Expected Yield/Acre'),
        ),
    ]
