# Generated by Django 2.0.2 on 2018-07-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180728_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop_requirements',
        ),
    ]
