# Generated by Django 2.0.2 on 2018-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_crop_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(default='', max_length=70, verbose_name='Crop')),
                ('temp_min', models.CharField(default='', max_length=50, verbose_name=' Min Temperature')),
                ('temp_max', models.CharField(default='', max_length=50, verbose_name='Max Temperature')),
                ('min_rainfall', models.CharField(default='', max_length=50, verbose_name='Min Rainfall')),
                ('max_rainfall', models.CharField(default='', max_length=50, verbose_name='Max Rainfall')),
                ('fertilizer_ha', models.CharField(default='', max_length=100, verbose_name='Fertilizer/Ha')),
                ('min_expected_acre', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Max Expected Yield/Acre')),
                ('max_expected_acre', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name=' Min Expected Yield/Acre')),
            ],
        ),
    ]
