# Generated by Django 2.0.2 on 2018-08-04 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_expenses_farm_productio'),
    ]

    operations = [
        migrations.CreateModel(
            name='farm_production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, max_length=4, verbose_name='Year')),
                ('production_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Production Amount in Kgs')),
                ('dateRecorded', models.DateTimeField(default=datetime.datetime(2018, 8, 4, 18, 10, 34, 722894), verbose_name='Date')),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Farm')),
            ],
        ),
        migrations.RemoveField(
            model_name='farm_productio',
            name='farm_id',
        ),
        migrations.AddField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 4, 18, 10, 34, 721896), verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='farm_productio',
        ),
    ]
