# Generated by Django 2.0.2 on 2018-08-05 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180804_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 23, 21, 41, 807154), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='farm',
            name='type',
            field=models.CharField(choices=[('wheat', 'Wheat'), ('maize', 'Maize')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 23, 21, 41, 808155), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='year',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='Year'),
        ),
    ]
