# Generated by Django 2.0.2 on 2018-08-06 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180806_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 12, 17, 40, 709336), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 12, 17, 40, 710336), verbose_name='Date'),
        ),
    ]
