# Generated by Django 2.0.2 on 2018-08-06 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180806_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 21, 0, 49, 591810), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 21, 0, 49, 592810), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='production_amount',
            field=models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Production Amount in Kgs'),
        ),
    ]
