# Generated by Django 2.0.2 on 2018-08-11 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180809_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv_data',
            name='date_uploaded',
        ),
        migrations.AddField(
            model_name='csv_data',
            name='cropName',
            field=models.CharField(max_length=100, null=True, verbose_name='Crop Name'),
        ),
        migrations.AddField(
            model_name='csv_data',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 8, 1, 651240), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='csv_data',
            name='maxCropYield',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True, verbose_name='Max Yield Per Acre(Bags)'),
        ),
        migrations.AddField(
            model_name='csv_data',
            name='minCropYield',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True, verbose_name='Max Yield Per Acre(Bags)'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 8, 1, 651240), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 8, 1, 651240), verbose_name='Date'),
        ),
    ]
