# Generated by Django 2.0.2 on 2018-08-11 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180811_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_data',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 16, 35, 60692), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 16, 35, 65674), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 16, 35, 65674), verbose_name='Date'),
        ),
    ]
