# Generated by Django 2.0.2 on 2018-08-11 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180811_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_data',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 20, 34, 374649), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='csv_data',
            name='minCropYield',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True, verbose_name='Min Yield Per Acre(Bags)'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 20, 34, 378649), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 16, 20, 34, 379649), verbose_name='Date'),
        ),
    ]
