# Generated by Django 2.0.2 on 2018-08-13 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180812_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='location',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='csv_data',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 11, 43, 42, 596722), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 11, 43, 42, 599699), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 11, 43, 42, 599699), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 11, 43, 42, 600699), verbose_name='Date'),
        ),
    ]
