# Generated by Django 2.0.2 on 2018-08-13 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180813_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_data',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 19, 34, 50, 512704), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 19, 34, 50, 515702), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 19, 34, 50, 514702), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='farm_production',
            name='dateRecorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 19, 34, 50, 516701), verbose_name='Date'),
        ),
    ]
